server:
  build: server
  ports:
    - "5556-5559"
  volumes:
    - ./config:/spacerace/config
    - ./maps:/spacerace/maps

frontend:
  build: frontend
  links:
    - server
  ports:
    - "8000:8000"
  volumes:
    - ./config:/spacerace/config
    - ./maps:/spacerace/maps

httpserver:
  build: httpserver
  links:
    - server

nginx:
  build: nginx
  ports:
    - "5001:5001"
  links:
    - httpserver

